dns:
  cached:
    fields:
      - query_contant
      - rewrite_ttl
      - query_type
      - query_result
      - conn_id
      - spendtime
      - dns_action
  exchanged:
    fields:
      - query_contant
      - rewrite_ttl
      - query_type
      - query_result
      - conn_id
      - spendtime
      - dns_action
  lookup:
    fields:
      - query_contant
      - rewrite_ttl
      - query_type
      - query_result
      - conn_id
      - spendtime
      - dns_action